## Weaviate workshop

<a target="_blank" href="https://colab.research.google.com/github/weaviate-tutorials/intro-workshop/blob/main/workshop.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

### Goals:

#### What you will see:


- Create a vector database with Weaviate,
- Add data to the database, and
- Interact with the data, including searching, and using LLMs with your data in Weaviate

### You will learn today:

- What Weaviate is,
- How it stores the data (based on its "meaning"), and
- What you can do with Weaviate, like semantic searches, and using LLMs to transform data.

Install the Weaviate python client, for environments that don't yet have it.

In [1]:
# !pip install -U weaviate-client

## Preparation: Get the data

We'll use a dataset of movies from TMDB. 

Pre-processed version: "./data/movies.csv"

Load (or download) the data, and preview it

In [2]:
import pandas as pd

# movie_df = pd.read_csv("./data/movies.csv")
movie_df = pd.read_csv("https://raw.githubusercontent.com/weaviate-tutorials/intro-workshop/main/data/movies.csv")
movie_df.head()

,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count,year
0,/rH0DPF7pB35jxLxKb3JRUgCrrnp.jpg,"[10751, 14, 16, 10749]",11224,en,Cinderella,Cinderella has faith her dreams of a better li...,100.819,/avz6S9HYWs4O8Oe4PenBFNX4uDi.jpg,1950-02-22,Cinderella,False,7.044,6523,1950
1,/p47ihFj4A7EpBjmPHdTj4ipyq1S.jpg,[18],599,en,Sunset Boulevard,A hack screenwriter writes a screenplay for a ...,57.740,/sC4Dpmn87oz9AuxZ15Lmip0Ftgr.jpg,1950-08-10,Sunset Boulevard,False,8.312,2485,1950
2,/zyO6j74DKMWfp5snWg6Hwo0T3Mz.jpg,"[80, 18, 9648]",548,ja,羅生門,Brimming with action while incisively examinin...,21.011,/vL7Xw04nFMHwnvXRFCmYYAzMUvY.jpg,1950-08-26,Rashomon,False,8.091,2121,1950
3,/b4yiLlIFuiULuuLTxT0Pt1QyT6J.jpg,"[16, 10751, 14, 12]",12092,en,Alice in Wonderland,"On a golden afternoon, young Alice follows a W...",75.465,/20cvfwfaFqNbe9Fc3VEHJuPRxmn.jpg,1951-07-28,Alice in Wonderland,False,7.200,5697,1951
4,/mxf8hJJkHTCqZP3m4o8E1TtwHHs.jpg,"[35, 10749]",872,en,Singin' in the Rain,"In 1927 Hollywood, a silent film production co...",31.407,/w03EiJVHP8Un77boQeE7hg9DVdU.jpg,1952-04-09,Singin' in the Rain,False,8.200,3036,1952

## Step 1: Create a Weaviate instance (database)

This (Embedded Weaviate) is a quick way to create a Weaviate database. Note that this is suitable for evaluation use only, and currently not compatible with Windows (we are working on it 😉).

You can also use:
- A free sandbox with Weaviate Cloud Services
- Open-source Weaviate directly, available cross-platform with Docker/Kubernetes
- For Enterprise use, Weaviate can be deployed on-premises or in the cloud (e.g. via AWS, GCP, Azure)

In [3]:
!pip show weaviate-client

Name: weaviate-client
Version: 4.15.0
Summary: A python native Weaviate client
Home-page: https://github.com/weaviate/weaviate-python-client
Author: Weaviate
Author-email: hello@weaviate.io,
License: BSD 3-clause
Location: /Users/jphwang/code/weaviate-tutorials/intro-workshop/.venv/lib/python3.11/site-packages
Requires: authlib, deprecation, grpcio, grpcio-health-checking, grpcio-tools, httpx, pydantic, validators
Required-by: weaviate-agents

In [4]:
import weaviate
import os
import json

your_cohere_apikey = os.environ["COHERE_APIKEY"]

client = weaviate.connect_to_embedded(
    version="latest",
    headers={
        "X-Cohere-Api-Key": your_cohere_apikey,  # Replace this with your actual key
    },
    environment_variables={"ENABLE_API_BASED_MODULES": "true"}
)

{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"warning","log_level_env":"","msg":"log level not recognized, defaulting to info","time":"2025-06-03T14:52:44+01:00"}
{"action":"startup","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"Feature flag LD integration disabled: could not locate WEAVIATE_LD_API_KEY env variable","time":"2025-06-03T14:52:44+01:00"}
{"action":"startup","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","default_vectorizer_module":"none","level":"info","msg":"the default vectorizer modules is set to \"none\", as a result all new schema classes without an explicit vectorizer setting, will use this vectorizer","time":"2025-06-03T14:52:44+01:00"}
{"action":"startup","auto_schema_enabled":{},"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"auto schema enabled setting is set to \"\u0026{\u003cnil\u003e {{{} {0 0}} 0 0 {{} 0} {{} 0}} true}\"","time":"2025-06-03T14:52:44+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"No resource limits set, weaviate will use all available memory and CPU. To limit resources, set LIMIT_RESOURCES=true","time":"2025-06-03T14:52:44+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"module offload-s3 is enabled","time":"2025-06-03T14:52:44+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","flag_key":"collection-retrieval-strategy","level":"info","msg":"feature flag instantiated","time":"2025-06-03T14:52:44+01:00","tool":"feature_flag","value":"LeaderOnly"}
{"action":"cluster_api_startup","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"cluster api server is ready to handle requests on :51173","time":"2025-06-03T14:52:44+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"warning","msg":"Multiple vector spaces are present, GraphQL Explore and REST API list objects endpoint module include params has been disabled as a result.","time":"2025-06-03T14:52:44+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"open cluster service","servers":{"Embedded_at_8079":51174},"time":"2025-06-03T14:52:44+01:00"}
{"address":"192.168.1.189:51175","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"starting cloud rpc server ...","time":"2025-06-03T14:52:44+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"starting raft sub-system ...","time":"2025-06-03T14:52:44+01:00"}
{"address":"192.168.1.189:51174","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"tcp transport","tcpMaxPool":3,"tcpTimeout":10000000000,"time":"2025-06-03T14:52:44+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"loading local db","time":"2025-06-03T14:52:44+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"local DB successfully loaded","time":"2025-06-03T14:52:44+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"schema manager loaded","n":0,"time":"2025-06-03T14:52:44+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","metadata_only_voters":false,"msg":"construct a new raft node","name":"Embedded_at_8079","time":"2025-06-03T14:52:44+01:00"}
{"action":"raft","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","index":182,"level":"info","msg":"initial configuration","servers":"[[{Suffrage:Voter ID:Embedded_at_8079 Address:192.168.1.189:50055}]]","time":"2025-06-03T14:52:44+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","last_snapshot_index":0,"last_store_applied_index_on_start":184,"level":"info","msg":"raft node constructed","raft_applied_index":0,"raft_last_index":184,"time":"2025-06-03T14:52:44+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","hasState":true,"level":"info","msg":"raft init","time":"2025-06-03T14:52:44+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"attempting to join","remoteNodes":{"Embedded_at_8079":"192.168.1.189:51174"},"time":"2025-06-03T14:52:44+01:00"}
{"action":"raft","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","follower":{},"leader-address":"","leader-id":"","level":"info","msg":"entering follower state","time":"2025-06-03T14:52:44+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"attempted to join and failed","remoteNode":"192.168.1.189:51174","status":8,"time":"2025-06-03T14:52:44+01:00"}
{"action":"read_disk_use","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"warning","msg":"disk usage currently at 91.63%, threshold set to 80.00%","path":"/Users/jphwang/.local/share/weaviate","time":"2025-06-03T14:52:45+01:00"}
{"action":"set_shard_read_only","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"warning","msg":"Set READONLY, disk usage currently at 91.63%, threshold set to 90.00%","path":"/Users/jphwang/.local/share/weaviate","time":"2025-06-03T14:52:45+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"attempting to join","remoteNodes":{"Embedded_at_8079":"192.168.1.189:51174"},"time":"2025-06-03T14:52:45+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"attempted to join and failed","remoteNode":"192.168.1.189:51174","status":8,"time":"2025-06-03T14:52:45+01:00"}
{"action":"raft","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","last-leader-addr":"","last-leader-id":"","level":"warning","msg":"heartbeat timeout reached, starting election","time":"2025-06-03T14:52:46+01:00"}
{"action":"raft","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"entering candidate state","node":{},"term":80,"time":"2025-06-03T14:52:46+01:00"}
{"action":"raft","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"pre-vote successful, starting election","refused":0,"tally":1,"term":80,"time":"2025-06-03T14:52:46+01:00","votesNeeded":1}
{"action":"raft","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"election won","tally":1,"term":80,"time":"2025-06-03T14:52:46+01:00"}
{"action":"raft","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","leader":{},"level":"info","msg":"entering leader state","time":"2025-06-03T14:52:46+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","last_store_log_applied_index":184,"level":"info","log_index":184,"log_name":"LogCommand","log_type":0,"msg":"reloading local DB as RAFT and local DB are now caught up","time":"2025-06-03T14:52:46+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"reload local db: update schema ...","time":"2025-06-03T14:52:46+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","index":"Movie","level":"info","msg":"reload local index","time":"2025-06-03T14:52:46+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"configured versions","server_version":"1.31.0","time":"2025-06-03T14:52:46+01:00","version":"1.31.0"}
{"action":"grpc_startup","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"grpc server listening at [::]:50050","time":"2025-06-03T14:52:46+01:00"}
{"address":"192.168.1.189:51174","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"current Leader","time":"2025-06-03T14:52:46+01:00"}
{"action":"restapi_management","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"Serving weaviate at http://127.0.0.1:8079","time":"2025-06-03T14:52:46+01:00","version":"1.31.0"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"attempting to join","remoteNodes":{"Embedded_at_8079":"192.168.1.189:51174"},"time":"2025-06-03T14:52:46+01:00"}
{"action":"raft","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","command":0,"level":"info","msg":"updating configuration","server-addr":"192.168.1.189:51174","server-id":"Embedded_at_8079","servers":"[[{Suffrage:Voter ID:Embedded_at_8079 Address:192.168.1.189:51174}]]","time":"2025-06-03T14:52:46+01:00"}
{"action":"telemetry_push","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"telemetry started","payload":"\u0026{MachineID:0a6503f3-0245-4947-a1c0-e9329ad78d47 Type:INIT Version:1.31.0 ObjectsCount:0 OS:darwin Arch:arm64 UsedModules:[generative-cohere text2vec-cohere] CollectionsCount:1}","time":"2025-06-03T14:52:47+01:00"}

Retrieve Weaviate instance information to check our configuration.

In [5]:
client.get_meta()["version"]

'1.31.0'

{"action":"restore_from_disk","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"snapshots disabled, loading from commit log","time":"2025-06-03T14:52:48+01:00"}
{"action":"hnsw_load_commit_log_corruption","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"error","msg":"write-ahead-log ended abruptly, some elements may not have been recovered","path":"/Users/jphwang/.local/share/weaviate/movie/zm5vFvrqiKcF/vectors_overview.hnsw.commitlog.d/1748956113","time":"2025-06-03T14:52:48+01:00"}
{"action":"restore_from_disk","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","duration":"3.377792ms","level":"info","msg":"restored data from disk","time":"2025-06-03T14:52:48+01:00"}
{"action":"hnsw_prefill_cache_async","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"not waiting for vector cache prefill, running in background","time":"2025-06-03T14:52:48+01:00","wait_for_cache_prefill":false}
{"action":"restore_from_disk","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"snapshots disabled, loading from commit log","time":"2025-06-03T14:52:48+01:00"}
{"action":"hnsw_load_commit_log_corruption","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"error","msg":"write-ahead-log ended abruptly, some elements may not have been recovered","path":"/Users/jphwang/.local/share/weaviate/movie/zm5vFvrqiKcF/vectors_title.hnsw.commitlog.d/1748956113","time":"2025-06-03T14:52:48+01:00"}
{"action":"restore_from_disk","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","duration":"1.923917ms","level":"info","msg":"restored data from disk","time":"2025-06-03T14:52:48+01:00"}
{"action":"hnsw_prefill_cache_async","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"not waiting for vector cache prefill, running in background","time":"2025-06-03T14:52:48+01:00","wait_for_cache_prefill":false}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"Completed loading shard movie_zm5vFvrqiKcF in 138.51025ms","time":"2025-06-03T14:52:48+01:00"}
{"action":"hnsw_vector_cache_prefill","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","count":5000,"index_id":"vectors_overview","level":"info","limit":1000000000000,"msg":"prefilled vector cache","time":"2025-06-03T14:52:48+01:00","took":37383250}
{"action":"hnsw_vector_cache_prefill","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","count":5000,"index_id":"vectors_title","level":"info","limit":1000000000000,"msg":"prefilled vector cache","time":"2025-06-03T14:52:48+01:00","took":35685583}

## Step 2: Add data to Weaviate

### Add collection definition

The equivalent of a SQL "table", is called a "collection" in Weaviate, like they are in NoSQL databases.

In case I created a demo collection - let's delete it.

In [6]:
client.collections.delete("Movie")

And create a new collection definition here.
We'll set up a collection called "Movie" with:
- Two "named vectors" -> which will save different "meanings" of the data,
- A "generative" module -> which will allow us to use LLMs with our data, and
- Properties to save our movie data (which are like SQL columns).
    - Just the title, overview, year and popularity for now.

In [ ]:
from weaviate.classes.config import Configure, DataType, Property

client.collections.create(
    name="Movie",
    vectorizer_config=[
        Configure.NamedVectors.text2vec_cohere(
            name="title",
            source_properties=["title"]
        ),
        Configure.NamedVectors.text2vec_cohere(
            name="overview",
            source_properties=["title", "overview"]
        ),
    ],
    generative_config=Configure.Generative.cohere(),
    properties=[
        Property(
            name="title",
            data_type=DataType.TEXT,
        ),
        Property(
            name="overview",
            data_type=DataType.TEXT,
        ),
        Property(
            name="year",
            data_type=DataType.INT,
        ),
        Property(
            name="popularity",
            data_type=DataType.NUMBER,
        ),
    ]
)

{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"warning","msg":"prop len tracker file /Users/jphwang/.local/share/weaviate/movie/viZFXuuH5nXu/proplengths does not exist, creating new tracker","time":"2025-06-03T14:52:54+01:00"}
{"action":"restore_from_disk","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"snapshots disabled, loading from commit log","time":"2025-06-03T14:52:54+01:00"}
{"action":"restore_from_disk","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","duration":"219.416µs","level":"info","msg":"restored data from disk","time":"2025-06-03T14:52:54+01:00"}
{"action":"hnsw_prefill_cache_async","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"not waiting for vector cache prefill, running in background","time":"2025-06-03T14:52:54+01:00","wait_for_cache_prefill":false}
{"action":"hnsw_vector_cache_prefill","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","count":1000,"index_id":"vectors_overview","level":"info","limit":1000000000000,"msg":"prefilled vector cache","time":"2025-06-03T14:52:54+01:00","took":104500}
{"action":"restore_from_disk","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"snapshots disabled, loading from commit log","time":"2025-06-03T14:52:54+01:00"}
{"action":"restore_from_disk","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","duration":"111.75µs","level":"info","msg":"restored data from disk","time":"2025-06-03T14:52:54+01:00"}
{"action":"hnsw_prefill_cache_async","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"not waiting for vector cache prefill, running in background","time":"2025-06-03T14:52:54+01:00","wait_for_cache_prefill":false}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"Created shard movie_viZFXuuH5nXu in 8.439833ms","time":"2025-06-03T14:52:54+01:00"}
{"action":"hnsw_vector_cache_prefill","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","count":1000,"index_id":"vectors_title","level":"info","limit":1000000000000,"msg":"prefilled vector cache","time":"2025-06-03T14:52:54+01:00","took":97458}

> Tip: You can get example collection definitions in our documentation:
> - https://weaviate.io/developers/weaviate/manage-data/collections

Was our collection created successfully? Let's take a look

In [8]:
client.collections.exists("Movie")

True

### Add data

We'll add actual objects (SQL rows) to our data. 

First, let's build objects to add - and take a look at a couple.

In [9]:
data_columns = ['title', 'overview', 'year', 'popularity']

df = movie_df[data_columns]

df.head()

,title,overview,year,popularity
0,Cinderella,Cinderella has faith her dreams of a better li...,1950,100.819
1,Sunset Boulevard,A hack screenwriter writes a screenplay for a ...,1950,57.740
2,Rashomon,Brimming with action while incisively examinin...,1950,21.011
3,Alice in Wonderland,"On a golden afternoon, young Alice follows a W...",1951,75.465
4,Singin' in the Rain,"In 1927 Hollywood, a silent film production co...",1952,31.407

> If it all looks fine - let's add objects:
> - https://weaviate.io/developers/weaviate/manage-data/import

In [10]:
movies = client.collections.get("Movie")

with movies.batch.fixed_size(100) as batch:
    for i, row in df.iterrows():
        obj_body = {
            c: row[c] for c in data_columns
        }
        batch.add_object(
            properties=obj_body
        )

In [11]:
print(len(movies.batch.failed_objects))

0

#### Confirm data load

Do we have data? 

Let's get an object count

In [12]:
movies = client.collections.get("Movie")

movies.aggregate.over_all(total_count=True)

AggregateReturn(properties={}, total_count=1322)

Does the data look right?

Let's grab a few objects from Weaviate!

In [13]:
response = movies.query.fetch_objects(limit=3)
for o in response.objects:
    print(o.properties)

{'title': 'Horrible Bosses', 'overview': 'For Nick, Kurt and Dale, the only thing that would make the daily grind more tolerable would be to grind their intolerable bosses into dust. Quitting is not an option, so, with the benefit of a few-too-many drinks and some dubious advice from a hustling ex-con, the three friends devise a convoluted and seemingly foolproof plan to rid themselves of their respective employers... permanently.', 'year': 2011, 'popularity': 56.036}
{'title': 'Jigsaw', 'overview': "Law enforcement finds itself chasing the ghost of a man dead for over a decade, embroiled in a diabolical new game that's only just begun.", 'year': 2017, 'popularity': 92.571}
{'title': 'Cruella', 'overview': 'In 1970s London amidst the punk rock revolution, a young grifter named Estella is determined to make a name for herself with her designs. She befriends a pair of young thieves who appreciate her appetite for mischief, and together they are able to build a life for themselves on the London streets. One day, Estella’s flair for fashion catches the eye of the Baroness von Hellman, a fashion legend who is devastatingly chic and terrifyingly haute. But their relationship sets in motion a course of events and revelations that will cause Estella to embrace her wicked side and become the raucous, fashionable and revenge-bent Cruella.', 'year': 2021, 'popularity': 106.998}

Let's pause for a second - because we've done a lot!

#### What did we just do?

Here is a conceptual diagram

<img src="./images/object_import_process_vectorizer.png" width="800">

You can, also, manage the vectorization outside of Weaviate, and import pre-vectorized data.

![img](./images/object_import_process_byov.png)

## Step 3: Work with the data

Let's try a few more involved queries

### Filtering (similar to WHERE filter in SQL)

Let's find objects that meet a particular condition.

In [14]:
import weaviate.classes.query as wq

response = movies.query.fetch_objects(
    filters=wq.Filter.by_property("year").greater_than(2015),
    limit=3
)

for o in response.objects:
    print(o.properties["title"])

Ghostbusters
Deadpool
Arrival

But this does not rank the result in any meaningful way. 

For that, we need a keyword search (as opposed to a keyword *filter*).

### Keyword search

Unlike a keyword filter, a keyword search will search for, and rank results based on the frequency of the keyword.

In [15]:
response = movies.query.bm25(
    query="galaxy",
    limit=5,
    return_metadata=wq.MetadataQuery(score=True, last_update_time=True)
)

for o in response.objects:
    print(o.metadata.score)
    print(o.metadata.last_update_time)
    print(o.properties)

4.875419616699219
2025-06-03 13:53:01.546000+00:00
{'title': 'Galaxy Quest', 'overview': 'For four years, the courageous crew of the NSEA protector - "Commander Peter Quincy Taggart" (Tim Allen), "Lt. Tawny Madison (Sigourney Weaver) and "Dr.Lazarus" (Alan Rickman) - set off on a thrilling and often dangerous mission in space...and then their series was cancelled! Now, twenty years later, aliens under attack have mistaken the Galaxy Quest television transmissions for "historical documents" and beam up the crew of has-been actors to save the universe. With no script, no director and no clue, the actors must turn in the performances of their lives.', 'year': 1999, 'popularity': 62.01}
3.216853141784668
2025-06-03 13:53:01.591000+00:00
{'overview': 'Following an assassination attempt on Senator Padmé Amidala, Jedi Knights Anakin Skywalker and Obi-Wan Kenobi investigate a mysterious plot that could change the galaxy forever.', 'year': 2002, 'title': 'Star Wars: Episode II - Attack of the Clones', 'popularity': 44.575}
2.9749975204467773
2025-06-03 13:53:03.321000+00:00
{'title': 'Alien: Covenant', 'overview': 'The crew of the colony ship Covenant, bound for a remote planet on the far side of the galaxy, discovers what they think is an uncharted paradise but is actually a dark, dangerous world.', 'year': 2017, 'popularity': 235.941}
2.1187729835510254
2025-06-03 13:53:02.338000+00:00
{'title': 'Star Trek', 'overview': 'The fate of the galaxy rests in the hands of bitter rivals. One, James Kirk, is a delinquent, thrill-seeking Iowa farm boy. The other, Spock, a Vulcan, was raised in a logic-based society that rejects all emotion. As fiery instinct clashes with calm reason, their unlikely but powerful partnership is the only thing capable of leading their crew through unimaginable danger, boldly going where no one has gone before. The human adventure has begun again.', 'year': 2009, 'popularity': 58.115}
1.9983925819396973
2025-06-03 13:53:03.616000+00:00
{'year': 2019, 'title': 'Dark Phoenix', 'overview': "The X-Men face their most formidable and powerful foe when one of their own, Jean Grey, starts to spiral out of control. During a rescue mission in outer space, Jean is nearly killed when she's hit by a mysterious cosmic force. Once she returns home, this force not only makes her infinitely more powerful, but far more unstable. The X-Men must now band together to save her soul and battle aliens that want to use Grey's new abilities to rule the galaxy.", 'popularity': 206.62}

<img src="./images/keyword_search_2.png" width="800">

<img src="./images/keyword_search_3.png" width="800">

### Semantic search

A semantic search, on the other hand, searches objects based on similarity

In [16]:
response = movies.query.near_text(
    query="galaxy",
    limit=3,
    target_vector="title",
    return_metadata=wq.MetadataQuery(distance=True)
)

for o in response.objects:
    print(o.metadata)
    print(json.dumps(o.properties, indent=2))

MetadataReturn(creation_time=None, last_update_time=None, distance=0.4862881898880005, certainty=None, score=None, explain_score=None, is_consistent=None, rerank_score=None)
{
  "title": "Galaxy Quest",
  "overview": "For four years, the courageous crew of the NSEA protector - \"Commander Peter Quincy Taggart\" (Tim Allen), \"Lt. Tawny Madison (Sigourney Weaver) and \"Dr.Lazarus\" (Alan Rickman) - set off on a thrilling and often dangerous mission in space...and then their series was cancelled! Now, twenty years later, aliens under attack have mistaken the Galaxy Quest television transmissions for \"historical documents\" and beam up the crew of has-been actors to save the universe. With no script, no director and no clue, the actors must turn in the performances of their lives.",
  "year": 1999,
  "popularity": 62.01
}
MetadataReturn(creation_time=None, last_update_time=None, distance=0.5379951000213623, certainty=None, score=None, explain_score=None, is_consistent=None, rerank_score=None)
{
  "title": "Guardians of the Galaxy Vol. 2",
  "overview": "The Guardians must fight to keep their newfound family together as they unravel the mysteries of Peter Quill's true parentage.",
  "year": 2017,
  "popularity": 142.267
}
MetadataReturn(creation_time=None, last_update_time=None, distance=0.5423773527145386, certainty=None, score=None, explain_score=None, is_consistent=None, rerank_score=None)
{
  "year": 1994,
  "title": "Stargate",
  "overview": "An interstellar teleportation device, found in Egypt, leads to a planet with humans resembling ancient Egyptians who worship the god Ra.",
  "popularity": 34.343
}

#### How does this work?

- Under the hood, this uses a vector search. It looks for objects which are the most similar to a text input.
- We can inspect the similarity along with the results.

In [17]:
response = movies.query.near_text(
    query="galaxy",
    limit=3,
    target_vector="title",  # or "overview"
    return_metadata=wq.MetadataQuery(distance=True)
)

for o in response.objects:
    print(o.metadata.distance)
    print(json.dumps(o.properties, indent=2))

0.4862881898880005
{
  "overview": "For four years, the courageous crew of the NSEA protector - \"Commander Peter Quincy Taggart\" (Tim Allen), \"Lt. Tawny Madison (Sigourney Weaver) and \"Dr.Lazarus\" (Alan Rickman) - set off on a thrilling and often dangerous mission in space...and then their series was cancelled! Now, twenty years later, aliens under attack have mistaken the Galaxy Quest television transmissions for \"historical documents\" and beam up the crew of has-been actors to save the universe. With no script, no director and no clue, the actors must turn in the performances of their lives.",
  "year": 1999,
  "title": "Galaxy Quest",
  "popularity": 62.01
}
0.5379951000213623
{
  "year": 2017,
  "title": "Guardians of the Galaxy Vol. 2",
  "overview": "The Guardians must fight to keep their newfound family together as they unravel the mysteries of Peter Quill's true parentage.",
  "popularity": 142.267
}
0.5423773527145386
{
  "title": "Stargate",
  "overview": "An interstellar teleportation device, found in Egypt, leads to a planet with humans resembling ancient Egyptians who worship the god Ra.",
  "year": 1994,
  "popularity": 34.343
}

This is where "vectors" come in. 

Each object in Weaviate includes a vector - like so:

In [18]:
response = movies.query.near_text(
    query="galaxy",
    limit=3,
    target_vector="title",
    include_vector=True,
    return_metadata=wq.MetadataQuery(distance=True)
)

for o in response.objects:
    print(o.metadata.distance)
    print(o.vector)
    print(json.dumps(o.properties, indent=2))

0.4862881898880005

These vector representations come from deep learning models to those that power LLMs. They capture meaning, and are called vector "embeddings".

<img src="./images/vector_search_2.png" width="800">

<img src="./images/vector_search_3.png" width="800">

### Hybrid search

A hybrid search combines results from both keyword and semantic searches.

In [19]:
response = movies.query.hybrid(
    query="galaxy",
    limit=3,
    target_vector="title",
    return_metadata=wq.MetadataQuery(score=True)
)

for o in response.objects:
    print(o.metadata.score)
    print(json.dumps(o.properties, indent=2))

1.0
{
  "title": "Galaxy Quest",
  "overview": "For four years, the courageous crew of the NSEA protector - \"Commander Peter Quincy Taggart\" (Tim Allen), \"Lt. Tawny Madison (Sigourney Weaver) and \"Dr.Lazarus\" (Alan Rickman) - set off on a thrilling and often dangerous mission in space...and then their series was cancelled! Now, twenty years later, aliens under attack have mistaken the Galaxy Quest television transmissions for \"historical documents\" and beam up the crew of has-been actors to save the universe. With no script, no director and no clue, the actors must turn in the performances of their lives.",
  "year": 1999,
  "popularity": 62.01
}
0.4180668890476227
{
  "overview": "The Guardians must fight to keep their newfound family together as they unravel the mysteries of Peter Quill's true parentage.",
  "year": 2017,
  "title": "Guardians of the Galaxy Vol. 2",
  "popularity": 142.267
}
0.39014044404029846
{
  "year": 1994,
  "title": "Stargate",
  "overview": "An interstellar teleportation device, found in Egypt, leads to a planet with humans resembling ancient Egyptians who worship the god Ra.",
  "popularity": 34.343
}

<img src="./images/hybrid_search_2.png" width="800">

<img src="./images/hybrid_search_3.png" width="800">

<img src="./images/hybrid_search_4.png" width="800">

### Generative search

A generative search transforms your data at retrieval time.

In [20]:
response = movies.generate.near_text(
    query="galaxy",
    limit=5,
    target_vector="title",
    single_prompt="Write a tweet promoting the movie with TITLE: {title} and OVERVIEW: {overview}.",
    grouped_task="What audience demographic might enjoy this group of movies?"
)

print(response.generated)
for o in response.objects:
    print(o.generative.text)
    print(json.dumps(o.properties, indent=2))

This group of movies primarily falls into the science fiction genre and features a mix of comedy, action, and adventure. The target audience for these films would likely include young adults and older teenagers who enjoy thrilling and humorous storylines set in space.

The inclusion of popular actors like Tim Allen, Sigourney Weaver, Alan Rickman, and Matt Damon could also attract a broader audience who are fans of these actors' work.

Additionally, the Guardians of the Galaxy series, being part of the Marvel Cinematic Universe, would draw in viewers who are invested in the expansive Marvel universe and its superheroes. The action and adventure elements, coupled with an intriguing storyline, make these movies appealing to audiences who enjoy swashbuckling, intergalactic adventures.

The films seem to have a broad appeal and could captivate a large audience, but the sci-fi comedy elements in Galaxy Quest and the Marvel fanbase may be the key demographics for this particular collection of movies.
"Hey, #SpaceGeeks! Buckle up for an intergalactic adventure like no other! The iconic crew of the NSEA Protector is back in action in Galaxy Quest. Prepare for laughter and thrills as these 'has-been' actors turn into unexpected heroes. A must-watch for all #SciFi fans! #GalaxyQuest #SpaceAdventures"
{
  "title": "Galaxy Quest",
  "overview": "For four years, the courageous crew of the NSEA protector - \"Commander Peter Quincy Taggart\" (Tim Allen), \"Lt. Tawny Madison (Sigourney Weaver) and \"Dr.Lazarus\" (Alan Rickman) - set off on a thrilling and often dangerous mission in space...and then their series was cancelled! Now, twenty years later, aliens under attack have mistaken the Galaxy Quest television transmissions for \"historical documents\" and beam up the crew of has-been actors to save the universe. With no script, no director and no clue, the actors must turn in the performances of their lives.",
  "year": 1999,
  "popularity": 62.01
}
"The Guardians are back! Get ready for an epic adventure in Guardians of the Galaxy Vol. 2! This time, the crew's family bonds are put to the test as they discover the secrets of Peter Quill's heritage. Action-packed and filled with laughter, it's a must-watch! #GuardiansoftheGalaxy #Vol2"
{
  "overview": "The Guardians must fight to keep their newfound family together as they unravel the mysteries of Peter Quill's true parentage.",
  "year": 2017,
  "title": "Guardians of the Galaxy Vol. 2",
  "popularity": 142.267
}
Travel through the #Stargate and discover a world of ancient Egyptian gods! This classic sci-fi adventure will take you on a thrilling journey through the cosmos. Prepare for an epic escape with the captivating story of humans worshipping Ra. #ScienceFiction #Adventure #StargateTravel
{
  "year": 1994,
  "title": "Stargate",
  "overview": "An interstellar teleportation device, found in Egypt, leads to a planet with humans resembling ancient Egyptians who worship the god Ra.",
  "popularity": 34.343
}
"Get ready for an epic adventure! Guardians of the Galaxy Vol. 3 is here! Join Peter Quill and the crew, as they grieve for Gamora and band together to save the universe. But will they fail this time? This thrilling ride could be the end of the Guardians! Don't miss out on this cosmic adventure! #GuardiansOfTheGalaxy #Vol3"
{
  "title": "Guardians of the Galaxy Vol. 3",
  "overview": "Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.",
  "year": 2023,
  "popularity": 165.416
}
Don't miss the thrilling tale of survival in space! Gravity, a nail-biting story of two astronauts cut off from their shuttle, left to drift into the vastness of space. Experience the terror of being alone in the cosmos! #Gravity
{
  "title": "Gravity",
  "overview": "Dr. Ryan Stone, a brilliant medical engineer on her first Shuttle mission, with veteran astronaut Matt Kowalsky in command of his last flight before retiring. But on a seemingly routine spacewalk, disaster strikes. The Shuttle is destroyed, leaving Stone and Kowalsky completely alone-tethered to nothing but each other and spiraling out into the blackness of space. The deafening silence tells them they have lost any link to Earth and any chance for rescue. As fear turns to panic, every gulp of air eats away at what little oxygen is left. But the only way home may be to go further out into the terrifying expanse of space.",
  "year": 2013,
  "popularity": 231.231
}

You can see here ⬆️ that each object has been transformed into a tweet by the LLM based on our prompt.

You can ask LLMs to perform all sorts of tasks

In [21]:
response = movies.generate.near_text(
    query="galaxy",
    target_vector="title",
    limit=3,
    single_prompt="Summarise the following movie overview into a short French sentence: {overview}."
)

for o in response.objects:
    print(o.generated)
    print(json.dumps(o.properties, indent=2))

Une vieille série TV de science-fiction est prise au mot par des aliens qui kidnappent ses acteurs pour leur faire jouer un rôle réel.
{
  "overview": "For four years, the courageous crew of the NSEA protector - \"Commander Peter Quincy Taggart\" (Tim Allen), \"Lt. Tawny Madison (Sigourney Weaver) and \"Dr.Lazarus\" (Alan Rickman) - set off on a thrilling and often dangerous mission in space...and then their series was cancelled! Now, twenty years later, aliens under attack have mistaken the Galaxy Quest television transmissions for \"historical documents\" and beam up the crew of has-been actors to save the universe. With no script, no director and no clue, the actors must turn in the performances of their lives.",
  "year": 1999,
  "title": "Galaxy Quest",
  "popularity": 62.01
}
Les Gardiens doivent se battre pour protéger leur nouvelle famille et découvrir les secrets de la parenté de Peter Quill.
{
  "title": "Guardians of the Galaxy Vol. 2",
  "overview": "The Guardians must fight to keep their newfound family together as they unravel the mysteries of Peter Quill's true parentage.",
  "year": 2017,
  "popularity": 142.267
}
Un portail interstellaire découvert en Égypte mène à une planète où des humains ressemblant aux anciens Égyptiens adorent le dieu Ra.
{
  "title": "Stargate",
  "overview": "An interstellar teleportation device, found in Egypt, leads to a planet with humans resembling ancient Egyptians who worship the god Ra.",
  "year": 1994,
  "popularity": 34.343
}

We can carry out multi-lingual tasks, because the underlying LLM is multi-lingual.

You can also send groups of results to the LLM with Weaviate.

In [22]:
response = movies.generate.near_text(
    query="galaxy",
    target_vector="title",
    limit=3,
    grouped_task="Write a poem about these movies"
)

print(response.generated)
for o in response.objects:
    print(json.dumps(o.properties, indent=2))

In the vastness of space, a tale unfolds,
A crew of actors, their story holds.
Galaxy Quest, a series of old,
Where brave explorers dared to bold.

Twenty years past, their show was lost,
But transmissions sent, at great cost.
Aliens interpreted, each scene and shot,
And beamed up the cast, to face what's sought.

Sigourney Weaver, Tim Allen too,
Embarking on a mission, what could they do?
Recreating scenes, the aliens knew,
To save the universe, their duty was true.

Guardians of the Galaxy, a band of misfits,
Fighting for family, with all their gifts.
Quill, the half-human, with roots unknown,
Unraveling mysteries, not alone.

Stargate, a portal to another realm,
Ancient Egyptians, a world unseen.
Worshipping Ra, the mighty god,
A journey awaits, where heroes are born.

Three tales, each unique, in the cosmos' vast sea,
Adventures that captivate and set us free.
From the big screen, these stories unfurled,
Leaving a trail of wonder and mirth.
{
  "title": "Galaxy Quest",
  "overview": "For four years, the courageous crew of the NSEA protector - \"Commander Peter Quincy Taggart\" (Tim Allen), \"Lt. Tawny Madison (Sigourney Weaver) and \"Dr.Lazarus\" (Alan Rickman) - set off on a thrilling and often dangerous mission in space...and then their series was cancelled! Now, twenty years later, aliens under attack have mistaken the Galaxy Quest television transmissions for \"historical documents\" and beam up the crew of has-been actors to save the universe. With no script, no director and no clue, the actors must turn in the performances of their lives.",
  "year": 1999,
  "popularity": 62.01
}
{
  "title": "Guardians of the Galaxy Vol. 2",
  "overview": "The Guardians must fight to keep their newfound family together as they unravel the mysteries of Peter Quill's true parentage.",
  "year": 2017,
  "popularity": 142.267
}
{
  "title": "Stargate",
  "overview": "An interstellar teleportation device, found in Egypt, leads to a planet with humans resembling ancient Egyptians who worship the god Ra.",
  "year": 1994,
  "popularity": 34.343
}

In [23]:
client.close()

{"action":"restapi_management","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"Shutting down... ","time":"2025-06-03T15:00:19+01:00","version":"1.31.0"}
{"action":"restapi_management","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"Stopped serving weaviate at http://127.0.0.1:8079","time":"2025-06-03T15:00:19+01:00","version":"1.31.0"}
{"action":"telemetry_push","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"telemetry terminated","payload":"\u0026{MachineID:0a6503f3-0245-4947-a1c0-e9329ad78d47 Type:TERMINATE Version:1.31.0 ObjectsCount:1322 OS:darwin Arch:arm64 UsedModules:[generative-cohere text2vec-cohere] CollectionsCount:1}","time":"2025-06-03T15:00:20+01:00"}
{"action":"cluster_api_shutdown","build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"server is shutting down","time":"2025-06-03T15:00:26+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"closing raft FSM store ...","time":"2025-06-03T15:00:26+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"shutting down raft sub-system ...","time":"2025-06-03T15:00:26+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"transferring leadership to another server","time":"2025-06-03T15:00:26+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","error":"cannot find peer","level":"error","msg":"transferring leadership","time":"2025-06-03T15:00:26+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"closing raft-net ...","time":"2025-06-03T15:00:26+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"closing log store ...","time":"2025-06-03T15:00:26+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"closing data store ...","time":"2025-06-03T15:00:26+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"closing loaded database ...","time":"2025-06-03T15:00:26+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"closing raft-rpc client ...","time":"2025-06-03T15:00:26+01:00"}
{"build_git_commit":"79499d6b63","build_go_version":"go1.24.3","build_image_tag":"HEAD","build_wv_version":"1.31.0","level":"info","msg":"closing raft-rpc server ...","time":"2025-06-03T15:00:26+01:00"}