## Weaviate workshop

<a target="_blank" href="https://colab.research.google.com/github/weaviate-tutorials/intro-workshop/blob/main/workshop.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

### Goals:

#### What you will see:


- Create a vector database with Weaviate,
- Add data to the database, and
- Interact with the data, including searching, and using LLMs with your data in Weaviate

### You will learn today:

- What Weaviate is,
- How it stores the data (based on its "meaning"), and
- What you can do with Weaviate, like semantic searches, and using LLMs to transform data.

Install the Weaviate python client, for environments that don't yet have it.

In [1]:
# !pip install -U weaviate-client

## Preparation: Get the data

We'll use a dataset of movies from TMDB. 

Pre-processed version: "./data/movies.csv"

Load (or download) the data, and preview it

In [2]:
import pandas as pd

# movie_df = pd.read_csv("./data/movies.csv")
movie_df = pd.read_csv("https://raw.githubusercontent.com/weaviate-tutorials/intro-workshop/main/data/movies.csv")
movie_df.head()

,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count,year
0,/rH0DPF7pB35jxLxKb3JRUgCrrnp.jpg,"[10751, 14, 16, 10749]",11224,en,Cinderella,Cinderella has faith her dreams of a better li...,100.819,/avz6S9HYWs4O8Oe4PenBFNX4uDi.jpg,1950-02-22,Cinderella,False,7.044,6523,1950
1,/p47ihFj4A7EpBjmPHdTj4ipyq1S.jpg,[18],599,en,Sunset Boulevard,A hack screenwriter writes a screenplay for a ...,57.740,/sC4Dpmn87oz9AuxZ15Lmip0Ftgr.jpg,1950-08-10,Sunset Boulevard,False,8.312,2485,1950
2,/zyO6j74DKMWfp5snWg6Hwo0T3Mz.jpg,"[80, 18, 9648]",548,ja,羅生門,Brimming with action while incisively examinin...,21.011,/vL7Xw04nFMHwnvXRFCmYYAzMUvY.jpg,1950-08-26,Rashomon,False,8.091,2121,1950
3,/b4yiLlIFuiULuuLTxT0Pt1QyT6J.jpg,"[16, 10751, 14, 12]",12092,en,Alice in Wonderland,"On a golden afternoon, young Alice follows a W...",75.465,/20cvfwfaFqNbe9Fc3VEHJuPRxmn.jpg,1951-07-28,Alice in Wonderland,False,7.200,5697,1951
4,/mxf8hJJkHTCqZP3m4o8E1TtwHHs.jpg,"[35, 10749]",872,en,Singin' in the Rain,"In 1927 Hollywood, a silent film production co...",31.407,/w03EiJVHP8Un77boQeE7hg9DVdU.jpg,1952-04-09,Singin' in the Rain,False,8.200,3036,1952

## Step 1: Create a Weaviate instance (database)

This (Embedded Weaviate) is a quick way to create a Weaviate database. Note that this is suitable for evaluation use only, and currently not compatible with Windows (we are working on it 😉).

You can also use:
- A free sandbox with Weaviate Cloud Services
- Open-source Weaviate directly, available cross-platform with Docker/Kubernetes
- For Enterprise use, Weaviate can be deployed on-premises or in the cloud (e.g. via AWS, GCP, Azure)

In [3]:
!pip show weaviate-client

Name: weaviate-client
Version: 4.16.9
Summary: A python native Weaviate client
Home-page: https://github.com/weaviate/weaviate-python-client
Author: Weaviate
Author-email: hello@weaviate.io,
License: BSD 3-clause
Location: /Users/jphwang/code/weaviate-tutorials/intro-workshop/.venv/lib/python3.11/site-packages
Requires: authlib, deprecation, grpcio, httpx, protobuf, pydantic, validators
Required-by: weaviate-agents

In [4]:
import weaviate
import os
import json

your_cohere_apikey = os.environ["COHERE_APIKEY"]

client = weaviate.connect_to_embedded(
    version="1.32.5",
    headers={
        "X-Cohere-Api-Key": your_cohere_apikey,  # Replace this with your actual key
    },
    environment_variables={"ENABLE_API_BASED_MODULES": "true"}
)

{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"warning","log_level_env":"","msg":"log level not recognized, defaulting to info","time":"2025-09-03T09:12:16+01:00"}
{"action":"startup","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"Feature flag LD integration disabled: could not locate WEAVIATE_LD_API_KEY env variable","time":"2025-09-03T09:12:16+01:00"}
{"action":"startup","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","default_vectorizer_module":"none","level":"info","msg":"the default vectorizer modules is set to \"none\", as a result all new schema classes without an explicit vectorizer setting, will use this vectorizer","time":"2025-09-03T09:12:16+01:00"}
{"action":"startup","auto_schema_enabled":true,"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"auto schema enabled setting is set to \"true\"","time":"2025-09-03T09:12:16+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"warning","msg":"Multiple vector spaces are present, GraphQL Explore and REST API list objects endpoint module include params has been disabled as a result.","time":"2025-09-03T09:12:16+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"No resource limits set, weaviate will use all available memory and CPU. To limit resources, set LIMIT_RESOURCES=true","time":"2025-09-03T09:12:16+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"module offload-s3 is enabled","time":"2025-09-03T09:12:16+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","flag_key":"collection-retrieval-strategy","level":"info","msg":"feature flag instantiated","time":"2025-09-03T09:12:16+01:00","tool":"feature_flag","value":"LeaderOnly"}
{"action":"cluster_api_startup","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"cluster api server is ready to handle requests on :64535","time":"2025-09-03T09:12:16+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"open cluster service","servers":{"Embedded_at_8079":64536},"time":"2025-09-03T09:12:16+01:00"}
{"address":"192.168.1.224:64537","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"starting cloud rpc server ...","time":"2025-09-03T09:12:16+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"starting raft sub-system ...","time":"2025-09-03T09:12:16+01:00"}
{"address":"192.168.1.224:64536","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"tcp transport","tcpMaxPool":3,"tcpTimeout":10000000000,"time":"2025-09-03T09:12:16+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"loading local db","time":"2025-09-03T09:12:16+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"local DB successfully loaded","time":"2025-09-03T09:12:16+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"schema manager loaded","n":0,"time":"2025-09-03T09:12:16+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","metadata_only_voters":false,"msg":"construct a new raft node","name":"Embedded_at_8079","time":"2025-09-03T09:12:16+01:00"}
{"action":"raft","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","index":462,"level":"info","msg":"initial configuration","servers":"[[{Suffrage:Voter ID:Embedded_at_8079 Address:192.168.1.224:64390}]]","time":"2025-09-03T09:12:16+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","last_snapshot_index":0,"last_store_applied_index_on_start":464,"level":"info","msg":"raft node constructed","raft_applied_index":0,"raft_last_index":464,"time":"2025-09-03T09:12:16+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","hasState":true,"level":"info","msg":"raft init","time":"2025-09-03T09:12:16+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"attempting to join","remoteNodes":{"Embedded_at_8079":"192.168.1.224:64536"},"time":"2025-09-03T09:12:16+01:00"}
{"action":"raft","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","follower":{},"leader-address":"","leader-id":"","level":"info","msg":"entering follower state","time":"2025-09-03T09:12:16+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"attempted to join and failed","remoteNode":"192.168.1.224:64536","status":8,"time":"2025-09-03T09:12:16+01:00"}
{"action":"read_disk_use","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"warning","msg":"disk usage currently at 86.16%, threshold set to 80.00%","path":"/Users/jphwang/.local/share/weaviate","time":"2025-09-03T09:12:17+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"attempting to join","remoteNodes":{"Embedded_at_8079":"192.168.1.224:64536"},"time":"2025-09-03T09:12:17+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"attempted to join and failed","remoteNode":"192.168.1.224:64536","status":8,"time":"2025-09-03T09:12:17+01:00"}
{"action":"raft","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","last-leader-addr":"","last-leader-id":"","level":"warning","msg":"heartbeat timeout reached, starting election","time":"2025-09-03T09:12:18+01:00"}
{"action":"raft","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"entering candidate state","node":{},"term":166,"time":"2025-09-03T09:12:18+01:00"}
{"action":"raft","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"pre-vote successful, starting election","refused":0,"tally":1,"term":166,"time":"2025-09-03T09:12:18+01:00","votesNeeded":1}
{"action":"raft","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"election won","tally":1,"term":166,"time":"2025-09-03T09:12:18+01:00"}
{"action":"raft","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","leader":{},"level":"info","msg":"entering leader state","time":"2025-09-03T09:12:18+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","last_store_log_applied_index":464,"level":"info","log_index":464,"log_name":"LogCommand","log_type":0,"msg":"reloading local DB as RAFT and local DB are now caught up","time":"2025-09-03T09:12:18+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"reload local db: update schema ...","time":"2025-09-03T09:12:18+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","index":"MTC","level":"info","msg":"reload local index","time":"2025-09-03T09:12:18+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","index":"Movies","level":"info","msg":"reload local index","time":"2025-09-03T09:12:18+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","index":"Movie","level":"info","msg":"reload local index","time":"2025-09-03T09:12:18+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","index":"Pages","level":"info","msg":"reload local index","time":"2025-09-03T09:12:18+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","index":"PDFPages","level":"info","msg":"reload local index","time":"2025-09-03T09:12:18+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","index":"Chunks","level":"info","msg":"reload local index","time":"2025-09-03T09:12:18+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"configured versions","server_version":"1.32.5","time":"2025-09-03T09:12:18+01:00","version":"1.32.5"}
{"action":"grpc_startup","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"grpc server listening at [::]:50050","time":"2025-09-03T09:12:18+01:00"}
{"action":"restapi_management","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"Serving weaviate at http://127.0.0.1:8079","time":"2025-09-03T09:12:18+01:00","version":"1.32.5"}
{"address":"192.168.1.224:64536","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"current Leader","time":"2025-09-03T09:12:18+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"attempting to join","remoteNodes":{"Embedded_at_8079":"192.168.1.224:64536"},"time":"2025-09-03T09:12:18+01:00"}
{"action":"raft","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","command":0,"level":"info","msg":"updating configuration","server-addr":"192.168.1.224:64536","server-id":"Embedded_at_8079","servers":"[[{Suffrage:Voter ID:Embedded_at_8079 Address:192.168.1.224:64536}]]","time":"2025-09-03T09:12:18+01:00"}
{"action":"telemetry_push","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"telemetry started","payload":"\u0026{MachineID:7f58f374-6902-4150-8954-a8d5bf67afa9 Type:INIT Version:1.32.5 ObjectsCount:0 OS:darwin Arch:arm64 UsedModules:[generative-cohere none text2vec-cohere text2vec-openai] CollectionsCount:6}","time":"2025-09-03T09:12:19+01:00"}
{"action":"restore_from_disk","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"snapshots disabled, loading from commit log","time":"2025-09-03T09:12:20+01:00"}
{"action":"restore_from_disk","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","duration":"424.708µs","level":"info","msg":"restored data from disk","time":"2025-09-03T09:12:20+01:00"}
{"action":"hnsw_prefill_cache_async","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"not waiting for vector cache prefill, running in background","time":"2025-09-03T09:12:20+01:00","wait_for_cache_prefill":false}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"Completed loading shard pdfpages_U2Ot69gglewW in 6.341917ms","time":"2025-09-03T09:12:20+01:00"}
{"action":"hnsw_vector_cache_prefill","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","count":1000,"index_id":"vectors_default","level":"info","limit":1000000000000,"msg":"prefilled vector cache","time":"2025-09-03T09:12:20+01:00","took":32833}
{"action":"restore_from_disk","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"snapshots disabled, loading from commit log","time":"2025-09-03T09:12:20+01:00"}
{"action":"restore_from_disk","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"snapshots disabled, loading from commit log","time":"2025-09-03T09:12:20+01:00"}
{"action":"restore_from_disk","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"snapshots disabled, loading from commit log","time":"2025-09-03T09:12:20+01:00"}
{"action":"restore_from_disk","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","duration":"192µs","level":"info","msg":"restored data from disk","time":"2025-09-03T09:12:20+01:00"}
{"action":"hnsw_prefill_cache_async","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"not waiting for vector cache prefill, running in background","time":"2025-09-03T09:12:20+01:00","wait_for_cache_prefill":false}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"Completed loading shard mtc_jphwang in 7.999292ms","time":"2025-09-03T09:12:20+01:00"}
{"action":"hnsw_vector_cache_prefill","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","count":1000,"index_id":"main","level":"info","limit":1000000000000,"msg":"prefilled vector cache","time":"2025-09-03T09:12:20+01:00","took":25250}
{"action":"restore_from_disk","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"snapshots disabled, loading from commit log","time":"2025-09-03T09:12:20+01:00"}
{"action":"restore_from_disk","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","duration":"1.123ms","level":"info","msg":"restored data from disk","time":"2025-09-03T09:12:20+01:00"}
{"action":"hnsw_prefill_cache_async","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"not waiting for vector cache prefill, running in background","time":"2025-09-03T09:12:20+01:00","wait_for_cache_prefill":false}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"Completed loading shard chunks_unkJPTqqGOiK in 9.794625ms","time":"2025-09-03T09:12:20+01:00"}
{"action":"restore_from_disk","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","duration":"3.030042ms","level":"info","msg":"restored data from disk","time":"2025-09-03T09:12:20+01:00"}
{"action":"hnsw_prefill_cache_async","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"not waiting for vector cache prefill, running in background","time":"2025-09-03T09:12:20+01:00","wait_for_cache_prefill":false}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"Completed loading shard movies_IZXrK6BEUgxC in 10.683625ms","time":"2025-09-03T09:12:20+01:00"}
{"action":"hnsw_vector_cache_prefill","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","count":3000,"index_id":"vectors_default","level":"info","limit":1000000000000,"msg":"prefilled vector cache","time":"2025-09-03T09:12:20+01:00","took":1134833}
{"action":"restore_from_disk","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"snapshots disabled, loading from commit log","time":"2025-09-03T09:12:20+01:00"}
{"action":"restore_from_disk","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","duration":"710.917µs","level":"info","msg":"restored data from disk","time":"2025-09-03T09:12:20+01:00"}
{"action":"hnsw_prefill_cache_async","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"not waiting for vector cache prefill, running in background","time":"2025-09-03T09:12:20+01:00","wait_for_cache_prefill":false}
{"action":"restore_from_disk","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"snapshots disabled, loading from commit log","time":"2025-09-03T09:12:20+01:00"}
{"action":"restore_from_disk","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","duration":"715.833µs","level":"info","msg":"restored data from disk","time":"2025-09-03T09:12:20+01:00"}
{"action":"hnsw_prefill_cache_async","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"not waiting for vector cache prefill, running in background","time":"2025-09-03T09:12:20+01:00","wait_for_cache_prefill":false}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"Completed loading shard movie_jFmvVlZv1F86 in 17.688875ms","time":"2025-09-03T09:12:20+01:00"}
{"action":"hnsw_vector_cache_prefill","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","count":3000,"index_id":"vectors_overview","level":"info","limit":1000000000000,"msg":"prefilled vector cache","time":"2025-09-03T09:12:20+01:00","took":5434958}
{"action":"hnsw_vector_cache_prefill","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","count":3000,"index_id":"vectors_title","level":"info","limit":1000000000000,"msg":"prefilled vector cache","time":"2025-09-03T09:12:20+01:00","took":6084167}
{"action":"hnsw_vector_cache_prefill","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","count":3000,"index_id":"vectors_default","level":"info","limit":1000000000000,"msg":"prefilled vector cache","time":"2025-09-03T09:12:20+01:00","took":53694125}

Retrieve Weaviate instance information to check our configuration.

In [5]:
client.get_meta()["version"]

'1.32.5'

## Step 2: Add data to Weaviate

### Add collection definition

The equivalent of a SQL "table", is called a "collection" in Weaviate, like they are in NoSQL databases.

In case I created a demo collection - let's delete it.

In [6]:
client.collections.delete("Movie")

And create a new collection definition here.
We'll set up a collection called "Movie" with:
- Two "named vectors" -> which will save different "meanings" of the data,
- A "generative" module -> which will allow us to use LLMs with our data, and
- Properties to save our movie data (which are like SQL columns).
    - Just the title, overview, year and popularity for now.

In [7]:
from weaviate.classes.config import Configure, DataType, Property

client.collections.create(
    name="Movie",
    vector_config=[
        Configure.Vectors.text2vec_cohere(
            name="title",
            source_properties=["title"]
        ),
        Configure.Vectors.text2vec_cohere(
            name="overview",
            source_properties=["title", "overview"]
        ),
    ],
    generative_config=Configure.Generative.cohere(),
    properties=[
        Property(
            name="title",
            data_type=DataType.TEXT,
        ),
        Property(
            name="overview",
            data_type=DataType.TEXT,
        ),
        Property(
            name="year",
            data_type=DataType.INT,
        ),
        Property(
            name="popularity",
            data_type=DataType.NUMBER,
        ),
    ]
)

{"action":"restore_from_disk","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","duration":"314.515042ms","level":"info","msg":"restored data from disk","time":"2025-09-03T09:12:20+01:00"}
{"action":"hnsw_prefill_cache_async","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"not waiting for vector cache prefill, running in background","time":"2025-09-03T09:12:20+01:00","wait_for_cache_prefill":false}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"Completed loading shard pages_UFQFlN4c9yuv in 321.677041ms","time":"2025-09-03T09:12:20+01:00"}

> Tip: You can get example collection definitions in our documentation:
> - https://weaviate.io/developers/weaviate/manage-data/collections

Was our collection created successfully? Let's take a look

In [8]:
client.collections.exists("Movie")

True

### Add data

We'll add actual objects (SQL rows) to our data. 

First, let's build objects to add - and take a look at a couple.

In [9]:
data_columns = ['title', 'overview', 'year', 'popularity']

df = movie_df[data_columns]

df.head()

,title,overview,year,popularity
0,Cinderella,Cinderella has faith her dreams of a better li...,1950,100.819
1,Sunset Boulevard,A hack screenwriter writes a screenplay for a ...,1950,57.740
2,Rashomon,Brimming with action while incisively examinin...,1950,21.011
3,Alice in Wonderland,"On a golden afternoon, young Alice follows a W...",1951,75.465
4,Singin' in the Rain,"In 1927 Hollywood, a silent film production co...",1952,31.407

> If it all looks fine - let's add objects:
> - https://weaviate.io/developers/weaviate/manage-data/import

In [10]:
movies = client.collections.get("Movie")

with movies.batch.fixed_size(100) as batch:
    for i, row in df.iterrows():
        obj_body = {
            c: row[c] for c in data_columns
        }
        batch.add_object(
            properties=obj_body
        )

{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"warning","msg":"prop len tracker file /Users/jphwang/.local/share/weaviate/movie/8mVXONsnIFuw/proplengths does not exist, creating new tracker","time":"2025-09-03T09:12:20+01:00"}
{"action":"restore_from_disk","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"snapshots disabled, loading from commit log","time":"2025-09-03T09:12:20+01:00"}
{"action":"restore_from_disk","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","duration":"66.708µs","level":"info","msg":"restored data from disk","time":"2025-09-03T09:12:20+01:00"}
{"action":"hnsw_prefill_cache_async","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"not waiting for vector cache prefill, running in background","time":"2025-09-03T09:12:20+01:00","wait_for_cache_prefill":false}
{"action":"hnsw_vector_cache_prefill","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","count":1000,"index_id":"vectors_overview","level":"info","limit":1000000000000,"msg":"prefilled vector cache","time":"2025-09-03T09:12:20+01:00","took":44333}
{"action":"restore_from_disk","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"snapshots disabled, loading from commit log","time":"2025-09-03T09:12:20+01:00"}
{"action":"restore_from_disk","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","duration":"111.334µs","level":"info","msg":"restored data from disk","time":"2025-09-03T09:12:20+01:00"}
{"action":"hnsw_prefill_cache_async","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"not waiting for vector cache prefill, running in background","time":"2025-09-03T09:12:20+01:00","wait_for_cache_prefill":false}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"Created shard movie_8mVXONsnIFuw in 2.020459ms","time":"2025-09-03T09:12:20+01:00"}
{"action":"hnsw_vector_cache_prefill","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","count":1000,"index_id":"vectors_title","level":"info","limit":1000000000000,"msg":"prefilled vector cache","time":"2025-09-03T09:12:20+01:00","took":26875}

In [11]:
print(len(movies.batch.failed_objects))

0

#### Confirm data load

Do we have data? 

Let's get an object count

In [12]:
movies = client.collections.get("Movie")

movies.aggregate.over_all(total_count=True)

AggregateReturn(properties={}, total_count=1322)

Does the data look right?

Let's grab a few objects from Weaviate!

In [13]:
response = movies.query.fetch_objects(limit=3)
for o in response.objects:
    print(o.properties)

{'title': 'E.T. the Extra-Terrestrial', 'overview': 'An alien is left behind on Earth and saved by the 10-year-old Elliot who decides to keep him hidden in his home. While a task force hunts for the extra-terrestrial, Elliot, his brother, and his little sister Gertie form an emotional bond with their new friend, and try to help him find his way home.', 'year': 1982, 'popularity': 62.64}
{'title': 'Prey', 'overview': 'When danger threatens her camp, the fierce and highly skilled Comanche warrior Naru sets out to protect her people. But the prey she stalks turns out to be a highly evolved alien predator with a technically advanced arsenal.', 'year': 2022, 'popularity': 197.532}
{'overview': 'In the post-apocalyptic future, reigning tyrannical supercomputers teleport a cyborg assassin known as the "Terminator" back to 1984 to kill Sarah Connor, whose unborn son is destined to lead insurgents against 21st century mechanical hegemony. Meanwhile, the human-resistance movement dispatches a lone warrior to safeguard Sarah. Can he stop the virtually indestructible killing machine?', 'year': 1984, 'title': 'The Terminator', 'popularity': 326.07}

Let's pause for a second - because we've done a lot!

#### What did we just do?

Here is a conceptual diagram

<img src="./images/object_import_process_vectorizer.png" width="800">

You can, also, manage the vectorization outside of Weaviate, and import pre-vectorized data.

![img](./images/object_import_process_byov.png)

## Step 3: Work with the data

Let's try a few more involved queries

### Filtering (similar to WHERE filter in SQL)

Let's find objects that meet a particular condition.

In [14]:
import weaviate.classes.query as wq

response = movies.query.fetch_objects(
    filters=wq.Filter.by_property("year").greater_than(2015),
    limit=3
)

for o in response.objects:
    print(o.properties["title"])

Ghostbusters
Deadpool
Arrival

But this does not rank the result in any meaningful way. 

For that, we need a keyword search (as opposed to a keyword *filter*).

### Keyword search

Unlike a keyword filter, a keyword search will search for, and rank results based on the frequency of the keyword.

In [15]:
response = movies.query.bm25(
    query="galaxy",
    limit=5,
    return_metadata=wq.MetadataQuery(score=True, last_update_time=True)
)

for o in response.objects:
    print(o.metadata.score)
    print(o.metadata.last_update_time)
    print(o.properties)

4.875419616699219
2025-09-03 08:12:22.110000+00:00
{'title': 'Galaxy Quest', 'overview': 'For four years, the courageous crew of the NSEA protector - "Commander Peter Quincy Taggart" (Tim Allen), "Lt. Tawny Madison (Sigourney Weaver) and "Dr.Lazarus" (Alan Rickman) - set off on a thrilling and often dangerous mission in space...and then their series was cancelled! Now, twenty years later, aliens under attack have mistaken the Galaxy Quest television transmissions for "historical documents" and beam up the crew of has-been actors to save the universe. With no script, no director and no clue, the actors must turn in the performances of their lives.', 'year': 1999, 'popularity': 62.01}
3.216853141784668
2025-09-03 08:12:22.331000+00:00
{'title': 'Star Wars: Episode II - Attack of the Clones', 'overview': 'Following an assassination attempt on Senator Padmé Amidala, Jedi Knights Anakin Skywalker and Obi-Wan Kenobi investigate a mysterious plot that could change the galaxy forever.', 'year': 2002, 'popularity': 44.575}
2.9749975204467773
2025-09-03 08:12:24.680000+00:00
{'overview': 'The crew of the colony ship Covenant, bound for a remote planet on the far side of the galaxy, discovers what they think is an uncharted paradise but is actually a dark, dangerous world.', 'year': 2017, 'title': 'Alien: Covenant', 'popularity': 235.941}
2.1187729835510254
2025-09-03 08:12:22.970000+00:00
{'title': 'Star Trek', 'overview': 'The fate of the galaxy rests in the hands of bitter rivals. One, James Kirk, is a delinquent, thrill-seeking Iowa farm boy. The other, Spock, a Vulcan, was raised in a logic-based society that rejects all emotion. As fiery instinct clashes with calm reason, their unlikely but powerful partnership is the only thing capable of leading their crew through unimaginable danger, boldly going where no one has gone before. The human adventure has begun again.', 'year': 2009, 'popularity': 58.115}
1.9983925819396973
2025-09-03 08:12:24.863000+00:00
{'title': 'Dark Phoenix', 'overview': "The X-Men face their most formidable and powerful foe when one of their own, Jean Grey, starts to spiral out of control. During a rescue mission in outer space, Jean is nearly killed when she's hit by a mysterious cosmic force. Once she returns home, this force not only makes her infinitely more powerful, but far more unstable. The X-Men must now band together to save her soul and battle aliens that want to use Grey's new abilities to rule the galaxy.", 'year': 2019, 'popularity': 206.62}

<img src="./images/keyword_search_2.png" width="800">

<img src="./images/keyword_search_3.png" width="800">

### Semantic search

A semantic search, on the other hand, searches objects based on similarity

In [16]:
response = movies.query.near_text(
    query="galaxy",
    limit=3,
    target_vector="title",
    return_metadata=wq.MetadataQuery(distance=True)
)

for o in response.objects:
    print(o.metadata)
    print(json.dumps(o.properties, indent=2))

MetadataReturn(creation_time=None, last_update_time=None, distance=0.46634727716445923, certainty=None, score=None, explain_score=None, is_consistent=None, rerank_score=None)
{
  "title": "Galaxy Quest",
  "overview": "For four years, the courageous crew of the NSEA protector - \"Commander Peter Quincy Taggart\" (Tim Allen), \"Lt. Tawny Madison (Sigourney Weaver) and \"Dr.Lazarus\" (Alan Rickman) - set off on a thrilling and often dangerous mission in space...and then their series was cancelled! Now, twenty years later, aliens under attack have mistaken the Galaxy Quest television transmissions for \"historical documents\" and beam up the crew of has-been actors to save the universe. With no script, no director and no clue, the actors must turn in the performances of their lives.",
  "year": 1999,
  "popularity": 62.01
}
MetadataReturn(creation_time=None, last_update_time=None, distance=0.523431658744812, certainty=None, score=None, explain_score=None, is_consistent=None, rerank_score=None)
{
  "title": "Guardians of the Galaxy Vol. 2",
  "overview": "The Guardians must fight to keep their newfound family together as they unravel the mysteries of Peter Quill's true parentage.",
  "year": 2017,
  "popularity": 142.267
}
MetadataReturn(creation_time=None, last_update_time=None, distance=0.5248526930809021, certainty=None, score=None, explain_score=None, is_consistent=None, rerank_score=None)
{
  "title": "Stargate",
  "overview": "An interstellar teleportation device, found in Egypt, leads to a planet with humans resembling ancient Egyptians who worship the god Ra.",
  "year": 1994,
  "popularity": 34.343
}

#### How does this work?

- Under the hood, this uses a vector search. It looks for objects which are the most similar to a text input.
- We can inspect the similarity along with the results.

In [17]:
response = movies.query.near_text(
    query="galaxy",
    limit=3,
    target_vector="title",  # or "overview"
    return_metadata=wq.MetadataQuery(distance=True)
)

for o in response.objects:
    print(o.metadata.distance)
    print(json.dumps(o.properties, indent=2))

0.46634727716445923
{
  "title": "Galaxy Quest",
  "overview": "For four years, the courageous crew of the NSEA protector - \"Commander Peter Quincy Taggart\" (Tim Allen), \"Lt. Tawny Madison (Sigourney Weaver) and \"Dr.Lazarus\" (Alan Rickman) - set off on a thrilling and often dangerous mission in space...and then their series was cancelled! Now, twenty years later, aliens under attack have mistaken the Galaxy Quest television transmissions for \"historical documents\" and beam up the crew of has-been actors to save the universe. With no script, no director and no clue, the actors must turn in the performances of their lives.",
  "year": 1999,
  "popularity": 62.01
}
0.523431658744812
{
  "title": "Guardians of the Galaxy Vol. 2",
  "overview": "The Guardians must fight to keep their newfound family together as they unravel the mysteries of Peter Quill's true parentage.",
  "year": 2017,
  "popularity": 142.267
}
0.5248526930809021
{
  "title": "Stargate",
  "overview": "An interstellar teleportation device, found in Egypt, leads to a planet with humans resembling ancient Egyptians who worship the god Ra.",
  "year": 1994,
  "popularity": 34.343
}

This is where "vectors" come in. 

Each object in Weaviate includes a vector - like so:

In [18]:
response = movies.query.near_text(
    query="galaxy",
    limit=3,
    target_vector="title",
    include_vector=True,
    return_metadata=wq.MetadataQuery(distance=True)
)

for o in response.objects:
    print(o.metadata.distance)
    print(o.vector)
    print(json.dumps(o.properties, indent=2))

0.46634727716445923

These vector representations come from deep learning models to those that power LLMs. They capture meaning, and are called vector "embeddings".

<img src="./images/vector_search_2.png" width="800">

<img src="./images/vector_search_3.png" width="800">

### Hybrid search

A hybrid search combines results from both keyword and semantic searches.

In [19]:
response = movies.query.hybrid(
    query="galaxy",
    limit=3,
    target_vector="title",
    return_metadata=wq.MetadataQuery(score=True)
)

for o in response.objects:
    print(o.metadata.score)
    print(json.dumps(o.properties, indent=2))

1.0
{
  "title": "Galaxy Quest",
  "overview": "For four years, the courageous crew of the NSEA protector - \"Commander Peter Quincy Taggart\" (Tim Allen), \"Lt. Tawny Madison (Sigourney Weaver) and \"Dr.Lazarus\" (Alan Rickman) - set off on a thrilling and often dangerous mission in space...and then their series was cancelled! Now, twenty years later, aliens under attack have mistaken the Galaxy Quest television transmissions for \"historical documents\" and beam up the crew of has-been actors to save the universe. With no script, no director and no clue, the actors must turn in the performances of their lives.",
  "year": 1999,
  "popularity": 62.01
}
0.35986092686653137
{
  "title": "Guardians of the Galaxy Vol. 2",
  "overview": "The Guardians must fight to keep their newfound family together as they unravel the mysteries of Peter Quill's true parentage.",
  "year": 2017,
  "popularity": 142.267
}
0.3475840389728546
{
  "title": "Stargate",
  "overview": "An interstellar teleportation device, found in Egypt, leads to a planet with humans resembling ancient Egyptians who worship the god Ra.",
  "year": 1994,
  "popularity": 34.343
}

<img src="./images/hybrid_search_2.png" width="800">

<img src="./images/hybrid_search_3.png" width="800">

<img src="./images/hybrid_search_4.png" width="800">

### Generative search

A generative search transforms your data at retrieval time.

In [20]:
response = movies.generate.near_text(
    query="galaxy",
    limit=5,
    target_vector="title",
    single_prompt="Write a tweet promoting the movie with TITLE: {title} and OVERVIEW: {overview}.",
    grouped_task="What audience demographic might enjoy this group of movies?"
)

print(response.generative.text)
for o in response.objects:
    print(o.generative.text)
    print(json.dumps(o.properties, indent=2))

This group of movies primarily falls into the science fiction genre and features a mix of space exploration, adventure, and comedy. The target audience for these movies can be mostly attributed to fans of sci-fi thrillers and those who appreciate a blend of action and imaginative storytelling.

However, each film has its own unique elements:

- Galaxy Quest has a more comedic approach, resembling a parody of science fiction series with a plot that involves the cast of a TV show being mistaken for real-life heroes. It could appeal to fans of sci-fi comedies and those who enjoy parodies.

- Guardians of the Galaxy Vol. 2 leans more towards the superhero genre, with a focus on action and a lively storyline. The Marvel Comics connection makes it accessible to fans of superhero movies and the comic book culture.

- Stargate has an ancient Egyptian theme running alongside the science fiction elements, which could attract viewers interested in archaeology, ancient civilizations, and the mystery surrounding Egyptian mythology.

- Star Wars, a classic in the science fiction world, has a vast and dedicated fan base. With its iconic characters, epic space battles, and legendary score, it holds a timeless appeal that cuts across generations. Both young and adult audiences continue to embrace the Star Wars franchise.

- Interstellar combines the adventure of space exploration with a heartfelt story about family and sacrifice. The emotional depth and breathtaking visuals attract viewers who appreciate a more serious, thought-provoking sci-fi experience.

Given the variety of tones and storylines within this group, the demographic reach is quite wide, spanning generations of movie enthusiasts. These films could appeal to teens and young adults, as well as older audiences who have grown up with the classic titles and remain captivated by the evolving world of science fiction.
"Hey, #SpaceGeeks! Buckle up for an intergalactic adventure like no other! The iconic crew of the NSEA Protector is back in action in Galaxy Quest. Prepare for laughter and thrills as these 'has-been' actors turn into unexpected heroes. A must-watch for all #SciFi fans! #GalaxyQuest #SpaceAdventure"
{
  "title": "Galaxy Quest",
  "overview": "For four years, the courageous crew of the NSEA protector - \"Commander Peter Quincy Taggart\" (Tim Allen), \"Lt. Tawny Madison (Sigourney Weaver) and \"Dr.Lazarus\" (Alan Rickman) - set off on a thrilling and often dangerous mission in space...and then their series was cancelled! Now, twenty years later, aliens under attack have mistaken the Galaxy Quest television transmissions for \"historical documents\" and beam up the crew of has-been actors to save the universe. With no script, no director and no clue, the actors must turn in the performances of their lives.",
  "year": 1999,
  "popularity": 62.01
}
"The Guardians are back! Get ready for an epic adventure in Guardians of the Galaxy Vol. 2! This time, the crew's family bonds are put to the test as they discover the secrets of Peter Quill's heritage. Action-packed and filled with laughter, it's a must-watch! #GotG2"
{
  "overview": "The Guardians must fight to keep their newfound family together as they unravel the mysteries of Peter Quill's true parentage.",
  "year": 2017,
  "title": "Guardians of the Galaxy Vol. 2",
  "popularity": 142.267
}
Travel through the #Stargate and discover a world of ancient Egyptian gods! This classic sci-fi adventure will take you on a thrilling journey through the cosmos. Prepare for an epic escape from our world to another, as the story unfolds in this must-watch film! #ScienceFiction #Adventure #StargateUniverse
{
  "title": "Stargate",
  "overview": "An interstellar teleportation device, found in Egypt, leads to a planet with humans resembling ancient Egyptians who worship the god Ra.",
  "year": 1994,
  "popularity": 34.343
}
"A galaxy-wide manhunt is on! Join Luke Skywalker, the daring Han Solo, and their faithful droids on a mission to save the galaxy's true hero, Princess Leia! #StarWars appeals to the hero in all of us. May the Force be with you!"
{
  "year": 1977,
  "title": "Star Wars",
  "overview": "Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.",
  "popularity": 250.715
}
Travel beyond the boundaries of our galaxy! 🌌
Embark on an epic adventure with #Interstellar, a thrilling tale of exploration! Prepare for an interstellar voyage like no other as our heroes navigate uncharted territories through a mysterious wormhole. Don't miss this epic space odyssey! 🎬🚀 #SpaceExplorers #WormholeAdventures
{
  "year": 2014,
  "title": "Interstellar",
  "overview": "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
  "popularity": 283.624
}

You can see here ⬆️ that each object has been transformed into a tweet by the LLM based on our prompt.

You can ask LLMs to perform all sorts of tasks

In [21]:
response = movies.generate.near_text(
    query="galaxy",
    target_vector="title",
    limit=3,
    single_prompt="Summarise the following movie overview into a short French sentence: {overview}."
)

for o in response.objects:
    print(o.generative.text)
    print(json.dumps(o.properties, indent=2))

Une série annulée il y a vingt ans est confondue avec de vrais documents historiques par des aliens et les acteurs sont enrôlés pour sauver l'univers.
{
  "title": "Galaxy Quest",
  "overview": "For four years, the courageous crew of the NSEA protector - \"Commander Peter Quincy Taggart\" (Tim Allen), \"Lt. Tawny Madison (Sigourney Weaver) and \"Dr.Lazarus\" (Alan Rickman) - set off on a thrilling and often dangerous mission in space...and then their series was cancelled! Now, twenty years later, aliens under attack have mistaken the Galaxy Quest television transmissions for \"historical documents\" and beam up the crew of has-been actors to save the universe. With no script, no director and no clue, the actors must turn in the performances of their lives.",
  "year": 1999,
  "popularity": 62.01
}
Les Gardiens doivent se battre pour protéger leur nouvelle famille et découvrir les secrets de la parenté de Peter Quill.
{
  "title": "Guardians of the Galaxy Vol. 2",
  "overview": "The Guardians must fight to keep their newfound family together as they unravel the mysteries of Peter Quill's true parentage.",
  "year": 2017,
  "popularity": 142.267
}
Un portail interstellaire découvert en Égypte mène à une planète où des humains ressemblant à des Égyptiens antiques adorent le dieu Ra.
{
  "overview": "An interstellar teleportation device, found in Egypt, leads to a planet with humans resembling ancient Egyptians who worship the god Ra.",
  "year": 1994,
  "title": "Stargate",
  "popularity": 34.343
}

We can carry out multi-lingual tasks, because the underlying LLM is multi-lingual.

You can also send groups of results to the LLM with Weaviate.

In [22]:
response = movies.generate.near_text(
    query="galaxy",
    target_vector="title",
    limit=3,
    grouped_task="Write a poem about these movies"
)

print(response.generative.text)
for o in response.objects:
    print(json.dumps(o.properties, indent=2))

{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"Metadata FSM reported caught up, starting replication engine","time":"2025-09-03T09:12:34+01:00"}
{"action":"replication_engine","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","engine":{},"level":"info","msg":"starting replication engine","node":"Embedded_at_8079","time":"2025-09-03T09:12:34+01:00"}
{"action":"replication_engine","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","consumer":{},"level":"info","msg":"starting replication engine consumer","node":"Embedded_at_8079","time":"2025-09-03T09:12:34+01:00"}
{"action":"replication_engine","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","component":"replication_consumer","level":"info","max_workers":10,"msg":"starting replication operation consumer","node":"Embedded_at_8079","op_timeout":86400000000000,"time":"2025-09-03T09:12:34+01:00"}
{"action":"replication_engine","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"starting replication engine producer","node":"Embedded_at_8079","producer":{},"time":"2025-09-03T09:12:34+01:00"}
{"action":"replication_engine","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","component":"replication_producer","level":"info","msg":"starting replication engine FSM producer","node":"Embedded_at_8079","polling_interval":5000000000,"time":"2025-09-03T09:12:34+01:00"}

In the vastness of space, a tale unfolds,
A story of heroes, of courage and bold,
Three films, a trilogy, a cosmic dance,
Each a gem, a space opera's romance.

"Galaxy Quest," a crew, once lost and found,
Their adventures, on a TV set, astound,
But fate's twist, aliens' mistake,
Beams them up, the real deal to face.

Sigourney, Tim, and Alan, a trio united,
Off on a mission, bravely fighting,
Through the stars, their ship so grand,
Protecting the universe, at their command.

Guardians of the Galaxy, a band of misfits,
Quill, Gamora, Groot, and Rocket's gifts,
In Vol. 2, their journey continues,
Unraveling secrets, of parentage and family ties.

Stargate, a portal to another realm,
Ancient Egyptians, a world unseen,
Ra, the god, a formidable foe,
An epic adventure, ready to go.

Three films, each a masterpiece,
Taking us to the stars, with ease,
A cosmic journey, an escape from the mundane,
A blast of excitement, a cinematic feast.

So, buckle up, embark on the quest,
Join the Guardians, let your spirit rest,
And through the Stargate, step into the unknown,
For these movies, in our hearts, are forever shown.
{
  "title": "Galaxy Quest",
  "overview": "For four years, the courageous crew of the NSEA protector - \"Commander Peter Quincy Taggart\" (Tim Allen), \"Lt. Tawny Madison (Sigourney Weaver) and \"Dr.Lazarus\" (Alan Rickman) - set off on a thrilling and often dangerous mission in space...and then their series was cancelled! Now, twenty years later, aliens under attack have mistaken the Galaxy Quest television transmissions for \"historical documents\" and beam up the crew of has-been actors to save the universe. With no script, no director and no clue, the actors must turn in the performances of their lives.",
  "year": 1999,
  "popularity": 62.01
}
{
  "year": 2017,
  "title": "Guardians of the Galaxy Vol. 2",
  "overview": "The Guardians must fight to keep their newfound family together as they unravel the mysteries of Peter Quill's true parentage.",
  "popularity": 142.267
}
{
  "year": 1994,
  "title": "Stargate",
  "overview": "An interstellar teleportation device, found in Egypt, leads to a planet with humans resembling ancient Egyptians who worship the god Ra.",
  "popularity": 34.343
}

In [23]:
client.close()

{"action":"restapi_management","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"Shutting down... ","time":"2025-09-03T09:12:36+01:00","version":"1.32.5"}
{"action":"restapi_management","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"Stopped serving weaviate at http://127.0.0.1:8079","time":"2025-09-03T09:12:36+01:00","version":"1.32.5"}
{"action":"telemetry_push","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"telemetry terminated","payload":"\u0026{MachineID:7f58f374-6902-4150-8954-a8d5bf67afa9 Type:TERMINATE Version:1.32.5 ObjectsCount:2430 OS:darwin Arch:arm64 UsedModules:[generative-cohere none text2vec-cohere text2vec-openai] CollectionsCount:6}","time":"2025-09-03T09:12:37+01:00"}
{"action":"cluster_api_shutdown","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"server is shutting down","time":"2025-09-03T09:12:43+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"closing replication engine ...","time":"2025-09-03T09:12:43+01:00"}
{"action":"replication_engine","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","component":"replication_consumer","error":"context canceled","level":"info","msg":"worker context canceled, shutting down consumer","time":"2025-09-03T09:12:43+01:00"}
{"action":"replication_engine","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","consumer":{},"level":"info","msg":"replication engine consumer stopped","node":"Embedded_at_8079","time":"2025-09-03T09:12:43+01:00"}
{"action":"replication_engine","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","engine":{},"level":"info","msg":"replication engine cancel request, shutting down","node":"Embedded_at_8079","time":"2025-09-03T09:12:43+01:00"}
{"action":"replication_engine","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","component":"replication_producer","level":"info","msg":"replication engine producer cancel request, stopping FSM producer","time":"2025-09-03T09:12:43+01:00"}
{"action":"replication_engine","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"replication engine producer stopped","node":"Embedded_at_8079","producer":{},"time":"2025-09-03T09:12:43+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"closing raft FSM store ...","time":"2025-09-03T09:12:43+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"shutting down raft sub-system ...","time":"2025-09-03T09:12:43+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"transferring leadership to another server","time":"2025-09-03T09:12:43+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","error":"cannot find peer","level":"error","msg":"transferring leadership","time":"2025-09-03T09:12:43+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"closing raft-net ...","time":"2025-09-03T09:12:43+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"closing log store ...","time":"2025-09-03T09:12:43+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"closing data store ...","time":"2025-09-03T09:12:43+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"closing loaded database ...","time":"2025-09-03T09:12:43+01:00"}
{"action":"hnsw_vector_cache_prefill","build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","count":101590,"index_id":"vectors_default","level":"info","limit":1000000000000,"msg":"prefilled vector cache","time":"2025-09-03T09:12:43+01:00","took":23260402416}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"closing raft-rpc client ...","time":"2025-09-03T09:12:43+01:00"}
{"build_git_commit":"08d409a988","build_go_version":"go1.25.0","build_image_tag":"HEAD","build_wv_version":"1.32.5","level":"info","msg":"closing raft-rpc server ...","time":"2025-09-03T09:12:43+01:00"}